### ISSUE TITLE
Letterbox even in fullscreen

### ISSUE THREAD

**Issue by riwim** [johanberonius/fullscreen-maps#1]
Hi,

when I use the bookmarklet the browser switches to fullscreen, but with the map is still in the same size. The rest auf the screen is filled with black and white "letterboxing" (see screenshot).
I'm using Safari (10.0.1) on macOS Sierra (10.12.1).

![screenshot](https://cloud.githubusercontent.com/assets/18545483/21000470/602057ee-bd1b-11e6-9097-9998bd850c55.png)

**Comment by johanberonius** [comment]
Ok, this seems to happen only with OpenStreetMap in Safari and Chrome. Not with Google or Bing maps and not in Firefox. I will see if I can fix it.

**Comment by johanberonius** [comment]
I think the map should be properly resized in fullscreen now. I have tested in Safari, Chrome and Firefox on Mac.
I have also updated the website at https://johanberonius.github.io/fullscreen-maps/
Thanks for the feedback, @riwim

**Comment by riwim** [comment]
I can confirm your tests. Thanks for the great work, @johanberonius
